# Generated by Django 3.0.6 on 2020-07-27 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.DateField(verbose_name='Group')),
                ('dtn', models.CharField(max_length=14, verbose_name='DTN')),
                ('date_received', models.DateField(help_text='Format: YYYY/MM/DD', verbose_name='Date Received')),
                ('received_from', models.CharField(max_length=250, verbose_name='Received from')),
                ('received_from_1', models.CharField(max_length=250, verbose_name='Received from (Company/Establishment Name)')),
                ('particulars', models.TextField()),
                ('endorsed_to', models.CharField(max_length=250, verbose_name='Endorsed to')),
                ('date_endorsed', models.DateField(help_text='Format: YYYY/MM/DD', verbose_name='Date Endorsed')),
                ('date_acted_upon', models.DateField(help_text='Format: YYYY/MM/DD', verbose_name='Date Acted Upon')),
                ('actions_taken', models.TextField()),
                ('document_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='incoming.DocumentType', verbose_name='Type of Document')),
                ('received_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
