# Generated by Django 3.0.6 on 2020-08-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incoming',
            old_name='dtn',
            new_name='tracking_number',
        ),
    ]
