# Generated by Django 3.0.6 on 2020-08-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0002_auto_20200811_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='group',
            field=models.DateField(verbose_name='Month'),
        ),
    ]
