# Generated by Django 3.0.6 on 2020-08-09 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterlist', '0017_qualifiedperson_status'),
        ('records', '0018_inspector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, '1. Unassigned'), (2, '2. Received by Inspector'), (3, '3. Returned to Client'), (4, '4. Forwarded to Supervisor'), (5, '5. Complete')], max_length=250)),
                ('tracking_number', models.CharField(max_length=12, verbose_name='DTN/Case No.')),
                ('group', models.DateField(verbose_name='Month')),
                ('applied_thru', models.CharField(choices=[('EPortal', 'EPortal'), ('Manual', 'Manual')], max_length=250)),
                ('application_type', models.CharField(choices=[('Initial', 'Initial'), ('Renewal', 'Renewal'), ('Variation', 'Variation')], max_length=250)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_received_by_rfo', models.DateField(verbose_name='Date Posted/Received')),
                ('date_forwarded_to_inspector', models.DateField(blank=True, null=True)),
                ('date_received_by_inspector', models.DateField(blank=True, null=True)),
                ('date_accomplished', models.DateField(blank=True, null=True, verbose_name='Eportal Accomplishment Date')),
                ('recommendation', models.CharField(choices=[('RL', 'RL'), ('RFD', 'RFD'), ('COC', 'COC'), ('N/A', 'N/A')], max_length=20)),
                ('date_received_by_supervisor', models.DateField(blank=True, null=True, verbose_name='Date Received by Supervisor (eportal)')),
                ('date_approved_by_supervisor', models.DateField(blank=True, null=True, verbose_name='Date Approved by Supervisor (eportal)')),
                ('processing_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('eod_1', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='w/in ARTA (w/o inspection)')),
                ('eod_2', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='w/in ARTA (w/ inspection)')),
                ('backlog', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('reason_1', models.TextField(blank=True, null=True, verbose_name='Reason for Backlog')),
                ('date_forwarded_to_center_1', models.DateField(blank=True, null=True, verbose_name='Date Forwarded to Center')),
                ('date_returned_by_center', models.DateField(blank=True, null=True)),
                ('reason_2', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('date_forwarded_to_center_2', models.DateField(blank=True, null=True, verbose_name='Date Forwarded to Center')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterlist.Establishment')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='records.Inspection')),
                ('licensing_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('type_of_variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.VariationType')),
            ],
        ),
    ]
