# Generated by Django 3.0.6 on 2020-08-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsreceived', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('1', '1. Unassigned'), ('2', '2. Received by Inspector'), ('3', '3. Returned to Client'), ('4', '4. Forwarded to Supervisor'), ('5', '5. Complete')], max_length=250),
        ),
    ]
