# Generated by Django 3.0.6 on 2020-08-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsreceived', '0002_auto_20200810_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Unassigned', '1. Unassigned'), ('Received by Inspector', '2. Received by Inspector'), ('Returned to Client', '3. Returned to Client'), ('Forwarded to Supervisor', '4. Forwarded to Supervisor'), ('Complete', '5. Complete')], max_length=250),
        ),
    ]
