# Generated by Django 3.0.6 on 2020-08-15 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appsreceived', '0003_auto_20200810_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='licensing_officer',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
