# Generated by Django 3.0.6 on 2020-08-15 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0020_auto_20200815_1411'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appsreceived', '0004_auto_20200815_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_thru',
            field=models.CharField(choices=[('EPortal', 'EPortal'), ('Manual', 'Manual')], default='EPortal', max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='licensing_officer',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Unassigned', '1. Unassigned'), ('Received by Inspector', '2. Received by Inspector'), ('Returned to Client', '3. Returned to Client'), ('Forwarded to Supervisor', '4. Forwarded to Supervisor'), ('Complete', '5. Complete')], default='Complete', max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='type_of_variation',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='masterlist.VariationType'),
            preserve_default=False,
        ),
    ]
