# Generated by Django 3.0.6 on 2020-08-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsreceived', '0005_auto_20200815_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_forwarded_to_inspector',
            field=models.DateField(verbose_name='Date Forwarded to Inspector'),
        ),
        migrations.AlterField(
            model_name='application',
            name='recommendation',
            field=models.CharField(choices=[('RL', 'RL'), ('RFD', 'RFD'), ('COC', 'COC'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
    ]
