# Generated by Django 3.0.6 on 2020-08-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsreceived', '0007_auto_20200815_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_number',
            field=models.CharField(max_length=14, verbose_name='DTN/Case No.'),
        ),
    ]
