# Generated by Django 3.0.6 on 2020-09-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsreceived', '0008_auto_20200815_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Renewal', 'Renewal'), ('Variation', 'Variation'), ('Turned Initial', 'Turned Initial')], max_length=250),
        ),
    ]
