# Generated by Django 3.0.6 on 2020-08-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterlist', '0020_auto_20200815_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('inspection_status', models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending')], max_length=250)),
                ('job_type', models.CharField(choices=[('PLI', 'Post Licensing Inspection'), ('REN', 'Renewal of LTO'), ('FUP', 'Followup Inspection'), ('RTN', 'Routine Inspection')], max_length=250, null=True)),
                ('establishment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='masterlist.Establishment')),
            ],
            options={
                'ordering': ['establishment__ltos__expiry'],
            },
        ),
    ]
