# Generated by Django 3.0.6 on 2020-05-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['establishment__ltos__expiry']},
        ),
    ]
