# Generated by Django 3.0.6 on 2020-06-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20200516_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='inspection_type',
            field=models.CharField(choices=[('PLI', 'Post Licensing Inspection'), ('REN', 'Renewal of LTO'), ('INI', 'Initial Inspection'), ('RTN', 'Routine Inspection'), ('SPA', 'Special Assignment'), ('VTN', 'Variation')], max_length=20, null=True),
        ),
    ]
