# Generated by Django 3.0.2 on 2020-04-12 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20200412_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='inspecion_status',
            new_name='inspection_status',
        ),
    ]
