# Generated by Django 3.0.6 on 2020-08-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20200608_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='inspection_type',
            field=models.CharField(choices=[('PLI', 'Post Licensing Inspection'), ('REN', 'Renewal of LTO'), ('INI', 'Initial Inspection'), ('RTN', 'Routine Inspection'), ('SPA', 'Special Assignment'), ('VTN', 'Variation'), ('CLS', 'For Verification of Closure')], max_length=20, null=True),
        ),
    ]
