# Generated by Django 3.0.2 on 2020-04-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20200412_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='inspection_type',
            field=models.CharField(choices=[('PLI', 'Post Licensing Inspection'), ('REN', 'Renewal of LTO'), ('INI', 'Initial Inspection'), ('RTN', 'Routine Inspection')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='inspection_status',
            field=models.CharField(default='pending', max_length=11),
        ),
    ]
