# Generated by Django 3.0.3 on 2020-04-13 06:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_auto_20200412_1205'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('renchecklist', django.db.models.manager.Manager()),
            ],
        ),
    ]
