# Generated by Django 3.0.2 on 2020-04-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0014_auto_20200413_2255'),
        ('checklist', '0005_auto_20200413_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='establishment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.Establishment'),
        ),
    ]
