# Generated by Django 3.0.6 on 2020-08-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.DateField(null=True, verbose_name='Month'),
        ),
    ]
