# Generated by Django 3.0.6 on 2020-08-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remarks',
            field=models.TextField(verbose_name='Remarks'),
        ),
    ]
