# Generated by Django 3.0.6 on 2020-08-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_auto_20200805_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productestablishment',
            name='lto',
        ),
        migrations.AddField(
            model_name='productestablishment',
            name='expiry',
            field=models.DateField(blank=True, help_text='Format: YYYY/MM/DD', null=True, verbose_name='expiry date'),
        ),
        migrations.AddField(
            model_name='productestablishment',
            name='lto_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
