# Generated by Django 3.0.6 on 2020-08-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_auto_20200805_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecificActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='productestablishment',
            name='specific_activity',
            field=models.ManyToManyField(to='pms.ProductSpecificActivity'),
        ),
    ]
