# Generated by Django 3.0.6 on 2020-08-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0008_auto_20200806_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='csl_reference_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CSL Control Ref. No.'),
        ),
    ]
