# Generated by Django 3.0.6 on 2020-08-08 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pms', '0010_auto_20200806_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInspector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], default='Complete', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inspector',
        ),
        migrations.AddField(
            model_name='productinspector',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_inspectors', to='pms.Product'),
        ),
        migrations.AddField(
            model_name='productinspector',
            name='product_inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
