# Generated by Django 3.0.6 on 2020-08-14 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_auto_20200808_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinspector',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inspectors', to='pms.Product'),
        ),
    ]
