# Generated by Django 3.0.6 on 2020-10-21 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0013_auto_20200814_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pms.ProductEstablishment', verbose_name='Establishment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Awaiting Result', 'Awaiting Result'), ('For Action', 'For Action'), ('Complete', 'Complete')], max_length=20),
        ),
    ]
