# Generated by Django 3.0.6 on 2020-10-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_auto_20201021_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_collected',
            field=models.DateField(null=True, verbose_name='Date Collected'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_referral',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Referral'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tracking_number',
            field=models.CharField(max_length=14, verbose_name='DTN/Case No.'),
        ),
    ]
