# Generated by Django 3.0.3 on 2020-05-07 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedOfficerDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('name', models.CharField(max_length=60)),
                ('center', models.CharField(choices=[('CFRR', 'CFRR'), ('CDRR', 'CDRR'), ('CCRR', 'CCRR'), ('CDRRHR', 'CDRRHR')], max_length=6)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Remarks')),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Active', max_length=8, null=True)),
                ('additional_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.AdditionalActivity')),
            ],
            options={
                'ordering': ['-date_modified'],
            },
            managers=[
                ('expiredlist', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('middle_initial', models.CharField(blank=True, max_length=3, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QualifiedPersonDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedOfficer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='masterlist.Person')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.AuthorizedOfficerDesignation')),
            ],
            bases=('masterlist.person',),
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='masterlist.Address')),
            ],
            bases=('masterlist.address',),
        ),
        migrations.CreateModel(
            name='PlantAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='masterlist.Address')),
            ],
            bases=('masterlist.address',),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Region')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='Lto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance', models.DateTimeField(blank=True, null=True, verbose_name='Date Issued')),
                ('lto_number', models.CharField(max_length=20)),
                ('expiry', models.DateTimeField(verbose_name='expiry date')),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ltos', to='masterlist.Establishment')),
            ],
            options={
                'ordering': ['-expiry'],
                'get_latest_by': 'expiry',
            },
        ),
        migrations.AddField(
            model_name='establishment',
            name='primary_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.PrimaryActivity'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='product_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.ProductLine'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.ProductType'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='specific_activity',
            field=models.ManyToManyField(to='masterlist.SpecificActivity'),
        ),
        migrations.CreateModel(
            name='CityOrMunicipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterlist.Province')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='municipality_or_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.CityOrMunicipality'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Province'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Region'),
        ),
        migrations.CreateModel(
            name='WarehouseAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='masterlist.Address')),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='masterlist.Establishment')),
            ],
            bases=('masterlist.address',),
        ),
        migrations.CreateModel(
            name='QualifiedPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='masterlist.Person')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.QualifiedPersonDesignation')),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Establishment')),
            ],
            bases=('masterlist.person',),
        ),
        migrations.AddField(
            model_name='establishment',
            name='authorized_officer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.AuthorizedOfficer'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='office_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.OfficeAddress'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='plant_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.PlantAddress'),
        ),
    ]
