# Generated by Django 3.0.2 on 2020-02-25 03:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedOfficerDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_inspection', models.CharField(choices=[('PLI', 'Post Licensing Inspection'), ('REN', 'Renewal of LTO'), ('INI', 'Initial Inspection')], max_length=20)),
                ('date_inspected', models.DateTimeField(verbose_name='date_inspected')),
                ('frequency_of_inspection', models.IntegerField(default=0)),
                ('date_of_followup_inspection', models.DateTimeField(verbose_name='date_followup_inspection')),
                ('inspector', models.CharField(choices=[('GGM', 'Giovanni G. Monang'), ('RTB', 'Rochelle T. Bayanes'), ('NDN', 'Nadia D. Navarro'), ('SOP', 'Saturnina O. Pandosen')], default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Lto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance', models.DateTimeField(verbose_name='date issued')),
                ('lto_number', models.CharField(max_length=20)),
                ('expiry', models.DateTimeField(verbose_name='expiry date')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QualifiedPersonDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedOfficer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='masterlist.Person')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.AuthorizedOfficerDesignation')),
            ],
            bases=('masterlist.person',),
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='masterlist.Address')),
            ],
            bases=('masterlist.address',),
        ),
        migrations.CreateModel(
            name='PlantAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='masterlist.Address')),
            ],
            bases=('masterlist.address',),
        ),
        migrations.CreateModel(
            name='WarehouseAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='masterlist.Address')),
            ],
            bases=('masterlist.address',),
        ),
        migrations.CreateModel(
            name='Radiologist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Region')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='CityOrMunicipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterlist.Province')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='municipality_or_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.CityOrMunicipality'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Province'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Region'),
        ),
        migrations.CreateModel(
            name='QualifiedPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='masterlist.Person')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.QualifiedPersonDesignation')),
            ],
            bases=('masterlist.person',),
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('application', models.CharField(choices=[('I', 'Initial'), ('R', 'Renewal'), ('V', 'Variation')], max_length=1)),
                ('name', models.CharField(max_length=60)),
                ('center', models.CharField(max_length=6)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('I', 'Inactive'), ('A', 'Active')], max_length=1, null=True)),
                ('additional_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.AdditionalActivity')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.Inspection')),
                ('lto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='masterlist.Lto')),
                ('primary_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.PrimaryActivity')),
                ('product_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.ProductLine')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.ProductType')),
                ('radiologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.Radiologist')),
                ('specific_activity', models.ManyToManyField(to='masterlist.SpecificActivity')),
                ('authorized_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.AuthorizedOfficer')),
                ('office_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.OfficeAddress')),
                ('plant_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.PlantAddress')),
                ('qualified_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.QualifiedPerson')),
                ('warehouse_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.WarehouseAddress')),
            ],
        ),
    ]
