# Generated by Django 3.0.3 on 2020-05-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lto',
            name='issuance',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY/MM/DD', null=True, verbose_name='Date Issued'),
        ),
    ]
