# Generated by Django 3.0.3 on 2020-05-08 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lto',
            name='current',
            field=models.CharField(default='N/A', max_length=255, verbose_name='To'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lto',
            name='old',
            field=models.CharField(default='N/A', max_length=255, verbose_name='From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lto',
            name='remarks',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lto',
            name='type_of_application',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Renewal', 'Renewal'), ('Variation', 'Variation')], default='Initial', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VariationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('primary_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterlist.PrimaryActivity')),
            ],
        ),
        migrations.AddField(
            model_name='lto',
            name='type_of_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.VariationType'),
        ),
    ]
