# Generated by Django 3.0.3 on 2020-05-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lto',
            name='expiry',
            field=models.DateTimeField(help_text='Format: YYYY/MM/DD', verbose_name='expiry date'),
        ),
    ]
