# Generated by Django 3.0.2 on 2020-02-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0002_auto_20200225_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='qualified_person',
        ),
        migrations.AddField(
            model_name='qualifiedperson',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Establishment'),
        ),
    ]
