# Generated by Django 3.0.3 on 2020-05-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0002_auto_20200511_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lto',
            name='lto_number',
            field=models.CharField(max_length=255),
        ),
    ]
