# Generated by Django 3.0.3 on 2020-05-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0002_auto_20200508_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationtype',
            name='type',
            field=models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major')], default='Major', max_length=20),
            preserve_default=False,
        ),
    ]
