# Generated by Django 3.0.3 on 2020-04-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0003_auto_20200407_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='warehouseaddress',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='masterlist.Establishment'),
        ),
    ]
