# Generated by Django 3.0.3 on 2020-05-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0003_variationtype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationtype',
            name='primary_activity',
        ),
    ]
