# Generated by Django 3.0.2 on 2020-02-29 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0003_auto_20200226_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='inspection',
        ),
        migrations.AddField(
            model_name='inspection',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Establishment'),
        ),
    ]
