# Generated by Django 3.0.3 on 2020-05-08 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0004_remove_variationtype_primary_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lto',
            name='current',
        ),
        migrations.RemoveField(
            model_name='lto',
            name='old',
        ),
        migrations.RemoveField(
            model_name='lto',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='lto',
            name='type_of_variation',
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_application', models.CharField(choices=[('Initial', 'Initial'), ('Renewal', 'Renewal'), ('Variation', 'Variation')], max_length=20)),
                ('old', models.CharField(help_text='Enter old value here (if applicable)', max_length=255, verbose_name='From')),
                ('current', models.CharField(help_text='Enter the new value here (if applicable)', max_length=255, verbose_name='To')),
                ('remarks', models.CharField(max_length=255)),
                ('lto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='masterlist.Lto')),
                ('type_of_variation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.VariationType')),
            ],
        ),
    ]
