# Generated by Django 3.0.2 on 2020-02-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0005_auto_20200229_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='type_of_inspection',
            field=models.CharField(choices=[('PLI', 'Post Licensing Inspection'), ('REN', 'Renewal of LTO'), ('INI', 'Initial Inspection'), ('RTN', 'Routine Inspection')], max_length=20),
        ),
    ]
