# Generated by Django 3.0.3 on 2020-04-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0005_auto_20200408_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='tracking_number',
            field=models.CharField(max_length=14, null=True, verbose_name='DTN or Case #'),
        ),
    ]
