# Generated by Django 3.0.6 on 2020-05-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0005_auto_20200515_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='center',
            field=models.CharField(choices=[('CFRR', 'CFRR'), ('CDRR', 'CDRR'), ('CCRR', 'CCRR'), ('CDRRHR', 'CDRRHR')], default='CDRR', max_length=6),
        ),
    ]
