# Generated by Django 3.0.3 on 2020-05-08 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0006_auto_20200508_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='additional_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.AdditionalActivity'),
        ),
        migrations.DeleteModel(
            name='EstAdditionalActivity',
        ),
    ]
