# Generated by Django 3.0.6 on 2020-05-16 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0006_auto_20200516_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='product_type',
            field=models.ForeignKey(default='Penicillin', on_delete=django.db.models.deletion.CASCADE, to='masterlist.ProductType'),
        ),
    ]
