# Generated by Django 3.0.2 on 2020-03-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0006_auto_20200229_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start_date')),
                ('approved_by', models.CharField(choices=[('GGM', 'Giovanni G. Monang'), ('RTB', 'Rochelle T. Bayanes'), ('NDN', 'Nadia D. Navarro'), ('SOP', 'Saturnina O. Pandosen')], max_length=10)),
                ('date_submitted', models.DateTimeField(verbose_name='date_submitted')),
                ('date_approved', models.DateTimeField(verbose_name='date_approved')),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CapaPreparator',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='masterlist.Person')),
            ],
            bases=('masterlist.person',),
        ),
        migrations.AddField(
            model_name='establishment',
            name='folder_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='risk_rating',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='CapaDeficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
                ('evidence', models.FileField(upload_to='')),
                ('type', models.CharField(choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Others', 'Others')], max_length=10)),
                ('proposed_comletion_date', models.DateTimeField()),
                ('inspector_comment', models.CharField(max_length=200)),
                ('accepted', models.BooleanField(default=False)),
                ('capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Capa')),
            ],
        ),
        migrations.AddField(
            model_name='capa',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.CapaPreparator'),
        ),
    ]
