# Generated by Django 3.0.2 on 2020-04-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0006_auto_20200408_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishment',
            options={'ordering': ['-date_modified']},
        ),
        migrations.AddField(
            model_name='establishment',
            name='inspection_status',
            field=models.CharField(choices=[('inspected', 'inspected'), ('uninspected', 'uninspected')], max_length=11, null=True),
        ),
    ]
