# Generated by Django 3.0.2 on 2020-04-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0007_auto_20200409_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='inspection_status',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
