# Generated by Django 3.0.6 on 2020-05-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0007_auto_20200516_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='product_type',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='masterlist.ProductType'),
        ),
        migrations.AlterField(
            model_name='estadditionalactivity',
            name='additional_activity',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='masterlist.AdditionalActivity'),
        ),
    ]
