# Generated by Django 3.0.2 on 2020-03-04 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0007_auto_20200304_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='capa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Capa'),
        ),
    ]
