# Generated by Django 3.0.3 on 2020-05-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0008_auto_20200508_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadditionalactivity',
            old_name='activity',
            new_name='additional_activity',
        ),
    ]
