# Generated by Django 3.0.2 on 2020-04-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0008_auto_20200409_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='checklist_status',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='inspection_status',
            field=models.CharField(default='hidden', max_length=11, null=True),
        ),
    ]
