# Generated by Django 3.0.3 on 2020-03-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0008_inspection_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capadeficiency',
            name='evidence',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='capadeficiency',
            name='inspector_comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
