# Generated by Django 3.0.3 on 2020-05-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0009_auto_20200508_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='product_line',
        ),
        migrations.CreateModel(
            name='EstProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterlist.Establishment')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterlist.ProductLine')),
            ],
        ),
    ]
