# Generated by Django 3.0.3 on 2020-03-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0009_auto_20200305_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='folder_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
