# Generated by Django 3.0.6 on 2020-05-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0009_auto_20200516_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadditionalactivity',
            name='additional_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterlist.AdditionalActivity'),
        ),
        migrations.AlterField(
            model_name='estproductline',
            name='product_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterlist.ProductLine'),
        ),
    ]
