# Generated by Django 3.0.2 on 2020-04-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0010_auto_20200411_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='checklist_status',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='inspection_status',
        ),
    ]
