# Generated by Django 3.0.3 on 2020-05-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0010_auto_20200508_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='remarks',
        ),
        migrations.AddField(
            model_name='estproductline',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Remarks'),
        ),
    ]
