# Generated by Django 3.0.3 on 2020-03-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0010_auto_20200305_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
