# Generated by Django 3.0.6 on 2020-05-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0011_auto_20200520_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lto',
            name='issuance',
            field=models.DateField(blank=True, help_text='Format: YYYY/MM/DD', null=True, verbose_name='Date Issued'),
        ),
    ]
