# Generated by Django 3.0.3 on 2020-03-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0011_auto_20200305_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
