# Generated by Django 3.0.3 on 2020-04-13 03:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0011_auto_20200412_2156'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='establishment',
            managers=[
                ('expiredlist', django.db.models.manager.Manager()),
            ],
        ),
    ]
