# Generated by Django 3.0.2 on 2020-04-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0012_auto_20200413_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='frequency_of_inspection',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Frequency of Inspection'),
        ),
    ]
