# Generated by Django 3.0.3 on 2020-03-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0012_auto_20200305_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='center',
            field=models.CharField(choices=[('CFRR', 'CFRR'), ('CDRR', 'CDRR'), ('CCRR', 'CCRR'), ('CDRRHR', 'CDRRHR')], max_length=6),
        ),
    ]
