# Generated by Django 3.0.3 on 2020-05-09 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0012_remove_variation_type_of_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='lto',
        ),
        migrations.AddField(
            model_name='lto',
            name='Variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masterlist.Variation'),
            preserve_default=False,
        ),
    ]
