# Generated by Django 3.0.3 on 2020-03-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0013_auto_20200305_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='lto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterlist.Lto'),
        ),
    ]
