# Generated by Django 3.0.6 on 2020-07-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0013_auto_20200619_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive (For unlicensed establishments)'), ('Closed', 'Closed (For closed establishments)'), ('Active', 'Active')], default='Active', max_length=8, null=True),
        ),
    ]
