# Generated by Django 3.0.3 on 2020-05-09 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0013_auto_20200509_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lto',
            name='Variation',
        ),
        migrations.AddField(
            model_name='variation',
            name='lto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='masterlist.Lto'),
            preserve_default=False,
        ),
    ]
