# Generated by Django 3.0.2 on 2020-04-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0013_auto_20200413_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='specific_activity',
            field=models.ManyToManyField(to='masterlist.SpecificActivity'),
        ),
    ]
