# Generated by Django 3.0.3 on 2020-03-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0014_auto_20200305_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='lto',
        ),
        migrations.AddField(
            model_name='lto',
            name='establishment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Establishment'),
        ),
    ]
