# Generated by Django 3.0.6 on 2020-08-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0014_auto_20200729_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date modified'),
        ),
    ]
