# Generated by Django 3.0.3 on 2020-04-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0014_auto_20200413_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
