# Generated by Django 3.0.2 on 2020-03-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0015_auto_20200305_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='authorized_officer',
        ),
        migrations.AddField(
            model_name='authorizedofficer',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.Establishment'),
        ),
        migrations.AlterField(
            model_name='lto',
            name='establishment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.Establishment'),
        ),
    ]
