# Generated by Django 3.0.2 on 2020-05-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0015_auto_20200509_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='current',
            field=models.CharField(help_text='Applicable only to variations whose old values will be replaced with new values. Put N/A if not applicable.', max_length=255, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='old',
            field=models.CharField(help_text='Applicable only to variations whose old values will be replaced with new values. Put N/A if not applicable', max_length=255, verbose_name='From'),
        ),
    ]
