# Generated by Django 3.0.3 on 2020-04-14 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0015_auto_20200414_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lto',
            options={'get_latest_by': 'expiry', 'ordering': ['-expiry']},
        ),
    ]
