# Generated by Django 3.0.6 on 2020-08-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0015_auto_20200806_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='lto',
            name='type_of_application',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Renewal', 'Renewal'), ('Variation', 'Variation'), ('Re-Issuance', 'Re-Issuance')], max_length=20),
        ),
    ]
