# Generated by Django 3.0.6 on 2020-08-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0016_auto_20200806_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifiedperson',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=20, null=True),
        ),
    ]
