# Generated by Django 3.0.2 on 2020-03-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0016_auto_20200305_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizedofficer',
            name='establishment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.Establishment'),
        ),
    ]
