# Generated by Django 3.0.3 on 2020-04-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0016_auto_20200414_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'get_latest_by': 'date_inspected', 'ordering': ['-date_inspected']},
        ),
    ]
