# Generated by Django 3.0.2 on 2020-04-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0017_auto_20200416_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='specific_activity',
            field=models.ManyToManyField(related_name='specific_activities', to='masterlist.SpecificActivity'),
        ),
    ]
