# Generated by Django 3.0.3 on 2020-03-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0017_auto_20200305_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='plant_address',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='warehouse_address',
        ),
        migrations.AddField(
            model_name='officeaddress',
            name='establishment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Establishment'),
        ),
        migrations.AddField(
            model_name='plantaddress',
            name='establishment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Establishment'),
        ),
        migrations.AddField(
            model_name='warehouseaddress',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Establishment'),
        ),
    ]
