# Generated by Django 3.0.6 on 2020-08-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0017_qualifiedperson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lto',
            name='expiry',
            field=models.DateField(blank=True, help_text='Format: YYYY/MM/DD', null=True, verbose_name='expiry date'),
        ),
        migrations.AlterField(
            model_name='lto',
            name='lto_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
