# Generated by Django 3.0.6 on 2020-08-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0019_auto_20200810_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationtype',
            name='type',
            field=models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major'), ('N/A', 'N/A')], max_length=20),
        ),
    ]
