# Generated by Django 3.0.3 on 2020-03-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0019_auto_20200306_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='capa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Capa'),
        ),
    ]
