# Generated by Django 3.0.3 on 2020-03-11 07:52

from django.db import migrations, models
import masterlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0020_auto_20200306_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_report',
            field=models.FileField(null=True, upload_to=masterlist.models.report_directory_path, verbose_name='Inspection Report'),
        ),
        migrations.AlterField(
            model_name='capadeficiency',
            name='evidence',
            field=models.FileField(blank=True, upload_to=masterlist.models.capa_attachments_directory_path),
        ),
    ]
