# Generated by Django 3.0.2 on 2020-03-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0020_auto_20200306_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capa',
            name='prepared_by',
        ),
        migrations.AddField(
            model_name='capapreparator',
            name='capa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.Capa'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='folder_id',
            field=models.CharField(max_length=10, null=True, verbose_name='Folder Number'),
        ),
    ]
