# Generated by Django 3.0.6 on 2020-09-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0020_auto_20200815_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='short_name',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
