# Generated by Django 3.1.4 on 2021-02-07 14:59

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0020_auto_20200815_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='municipality_or_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', on_delete=django.db.models.deletion.CASCADE, to='masterlist.cityormunicipality'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, to='masterlist.province'),
        ),
    ]
