# Generated by Django 3.0.2 on 2020-03-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0021_auto_20200311_1552'),
        ('masterlist', '0021_auto_20200309_2239'),
    ]

    operations = [
    ]
