# Generated by Django 3.0.3 on 2020-03-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0023_auto_20200312_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lto',
            name='issuance',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Issued'),
        ),
    ]
