# Generated by Django 3.0.2 on 2020-03-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0024_auto_20200312_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Remarks'),
        ),
    ]
