# Generated by Django 3.0.3 on 2020-03-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0025_auto_20200315_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capadeficiency',
            name='evidence',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='capadeficiency',
            name='proposed_comletion_date',
            field=models.DateTimeField(verbose_name='Proposed Completion Date'),
        ),
    ]
