# Generated by Django 3.0.2 on 2020-03-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0027_auto_20200321_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lto',
            name='establishment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='est', to='masterlist.Establishment'),
        ),
    ]
