# Generated by Django 3.0.4 on 2020-03-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0028_auto_20200321_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lto',
            name='establishment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterlist.Establishment'),
        ),
    ]
