# Generated by Django 3.0.4 on 2020-03-22 11:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0029_auto_20200321_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-date_inspected']},
        ),
        migrations.AlterModelManagers(
            name='establishment',
            managers=[
                ('plichecklist', django.db.models.manager.Manager()),
            ],
        ),
    ]
