# Generated by Django 3.0.4 on 2020-03-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0030_auto_20200322_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capadeficiency',
            options={'verbose_name': 'CAPA Deficiencies', 'verbose_name_plural': 'CAPA Deficiencies'},
        ),
        migrations.AlterModelOptions(
            name='capapreparator',
            options={'verbose_name': 'Preparedy by', 'verbose_name_plural': 'Prepared by'},
        ),
    ]
