# Generated by Django 3.0.3 on 2020-03-26 07:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0031_auto_20200323_0009'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='establishment',
            managers=[
                ('renchecklist', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='establishment',
            name='specific_activity',
            field=models.ManyToManyField(to='masterlist.SpecificActivity', verbose_name='Specific Activity/s'),
        ),
    ]
