# Generated by Django 3.0.2 on 2020-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0032_auto_20200326_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='date_of_followup_inspection',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Followup Inspection'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='frequency_of_inspection',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Frequency of Inspection'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='risk_rating',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=7, null=True),
        ),
    ]
