# Generated by Django 3.0.2 on 2020-04-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0034_auto_20200406_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lto',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ltos', to='masterlist.Establishment'),
        ),
    ]
