# Generated by Django 3.0.3 on 2020-04-07 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0035_auto_20200407_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lto',
            options={'ordering': ['-expiry']},
        ),
        migrations.RemoveField(
            model_name='officeaddress',
            name='establishment',
        ),
        migrations.RemoveField(
            model_name='plantaddress',
            name='establishment',
        ),
        migrations.AddField(
            model_name='establishment',
            name='office_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.OfficeAddress'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='plant_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.PlantAddress'),
        ),
    ]
