# Generated by Django 3.0.3 on 2020-04-07 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0036_auto_20200407_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizedofficer',
            name='establishment',
        ),
        migrations.AddField(
            model_name='establishment',
            name='authorized_officer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.AuthorizedOfficer'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='capa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.Capa'),
        ),
    ]
