# Generated by Django 3.0.2 on 2020-04-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200426_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(max_length=1),
        ),
    ]
