# Generated by Django 3.0.6 on 2020-07-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgoing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
