# Generated by Django 3.0.6 on 2020-07-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgoing', '0002_auto_20200728_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing',
            name='remarks',
            field=models.TextField(),
        ),
    ]
