# Generated by Django 3.0.6 on 2020-08-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outgoing', '0003_auto_20200729_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoing',
            old_name='dtn',
            new_name='tracking_number',
        ),
    ]
