# Generated by Django 3.0.6 on 2020-08-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgoing', '0004_auto_20200812_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
