# Generated by Django 3.0.6 on 2020-07-29 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0017_auto_20200729_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='PliStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.DateField(verbose_name='Month')),
                ('mother_dtn', models.CharField(blank=True, max_length=50, null=True)),
                ('date_forwarded_to_center', models.DateField()),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='records.Inspection')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pli.PliStatus')),
            ],
        ),
    ]
