# Generated by Django 3.0.6 on 2020-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pli', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pli',
            options={'verbose_name_plural': "PLI's"},
        ),
        migrations.AlterModelOptions(
            name='plistatus',
            options={'verbose_name_plural': 'PLI Status'},
        ),
        migrations.AlterField(
            model_name='pli',
            name='date_forwarded_to_center',
            field=models.DateField(blank=True, null=True),
        ),
    ]
