# Generated by Django 3.0.6 on 2020-07-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pli', '0003_auto_20200730_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pli',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pli.PliStatus'),
        ),
    ]
