# Generated by Django 3.0.3 on 2020-05-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa',
            name='date_approved',
            field=models.DateTimeField(help_text='Format: YYYY/MM/DD', verbose_name='date_approved'),
        ),
        migrations.AlterField(
            model_name='capa',
            name='date_submitted',
            field=models.DateTimeField(help_text='Format: YYYY/MM/DD', verbose_name='date_submitted'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='date_inspected',
            field=models.DateTimeField(help_text='Format: YYYY/MM/DD', verbose_name='Date Inspected'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='date_of_followup_inspection',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY/MM/DD', null=True, verbose_name='Date of Followup Inspection'),
        ),
    ]
