# Generated by Django 3.0.3 on 2020-05-11 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='frequency_of_inspection',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Leave blank if not applicable', null=True, verbose_name='Frequency of Inspection'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='remarks',
            field=models.CharField(help_text='Put inspection remarks here. Number each remark.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='risk_rating',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], help_text='Leave blank if not applicable', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='tracking_number',
            field=models.CharField(help_text='Put N/I if no DTN', max_length=14, null=True, verbose_name='DTN or Case #'),
        ),
    ]
