# Generated by Django 3.0.3 on 2020-05-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200511_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa',
            name='start_date',
            field=models.DateTimeField(help_text='Format: YYYY/MM/DD', verbose_name='start_date'),
        ),
    ]
