# Generated by Django 3.0.6 on 2020-05-20 16:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200520_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capa',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='capapreparator',
            name='capa',
        ),
        migrations.AddField(
            model_name='capa',
            name='date_prepared',
            field=models.DateField(default=datetime.date(2020, 5, 20), help_text='Format: YYYY/MM/DD', verbose_name='start_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capa',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='records.CapaPreparator'),
        ),
        migrations.AddField(
            model_name='capa',
            name='recommendation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capapreparator',
            name='designation',
            field=models.CharField(choices=[(1, 'Owner'), (2, 'CEO/President/General Manager'), (3, 'Head, Quality Assurance/Control'), (4, 'Head, Regulatory Affairs'), (5, 'Head, Production'), (6, 'Company Pharmacist'), (7, 'Production Manager/Head'), (8, 'Quality Assurance Manager/Head'), (9, 'Quality Control Manager/Head'), (10, 'Pharmacovigilance Officer'), (11, 'Authorized person for batch release'), (12, 'Production Manager/Head'), (13, 'Food safety compliance officer'), (14, 'Regulatory officer'), (15, 'Authorized Representative')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capa',
            name='date_approved',
            field=models.DateField(help_text='Format: YYYY/MM/DD', verbose_name='date_approved'),
        ),
        migrations.AlterField(
            model_name='capa',
            name='date_submitted',
            field=models.DateField(help_text='Format: YYYY/MM/DD', verbose_name='date_submitted'),
        ),
        migrations.AlterField(
            model_name='capa',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
