# Generated by Django 3.0.6 on 2020-05-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200520_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capadeficiency',
            name='proposed_comletion_date',
            field=models.DateField(verbose_name='Proposed Completion Date'),
        ),
    ]
