# Generated by Django 3.0.3 on 2020-05-11 07:10

from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200511_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_report',
            field=models.FileField(blank=True, null=True, upload_to=records.models.report_directory_path, verbose_name='Inspection Report'),
        ),
    ]
