# Generated by Django 3.0.6 on 2020-05-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200520_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='date_inspected',
            field=models.DateField(help_text='Format: YYYY/MM/DD', verbose_name='Date Inspected'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='date_of_followup_inspection',
            field=models.DateField(blank=True, help_text='Format: YYYY/MM/DD', null=True, verbose_name='Date of Followup Inspection'),
        ),
    ]
