# Generated by Django 3.0.6 on 2020-05-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20200520_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa',
            name='date_prepared',
            field=models.DateField(help_text='Format: YYYY/MM/DD', verbose_name='Date Prepared'),
        ),
        migrations.AlterField(
            model_name='capa',
            name='date_submitted',
            field=models.DateField(help_text='Format: YYYY/MM/DD', verbose_name='Date Submitted'),
        ),
    ]
