# Generated by Django 3.0.6 on 2020-05-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20200520_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capadeficiency',
            name='proposed_comletion_date',
            field=models.DateField(blank=True, verbose_name='Proposed Completion Date'),
        ),
        migrations.AlterField(
            model_name='capapreparator',
            name='designation',
            field=models.CharField(choices=[('Owner', 'Owner'), ('CEO/President/General Manager', 'CEO/President/General Manager'), ('Head, Quality Assurance/Control', 'Head, Quality Assurance/Control'), ('Head, Regulatory Affairs', 'Head, Regulatory Affairs'), ('Head, Production', 'Head, Production'), ('Company Pharmacist', 'Company Pharmacist'), ('Production Manager/Head', 'Production Manager/Head'), ('Quality Assurance Manager/Head', 'Quality Assurance Manager/Head'), ('Quality Control Manager/Head', 'Quality Control Manager/Head'), ('Pharmacovigilance Officer', 'Pharmacovigilance Officer'), ('Authorized person for batch release', 'Authorized person for batch release'), ('Production Manager/Head', 'Production Manager/Head'), ('Food safety compliance officer', 'Food safety compliance officer'), ('Regulatory officer', 'Regulatory officer'), ('Authorized Representative', 'Authorized Representative')], max_length=255, null=True),
        ),
    ]
