# Generated by Django 3.0.6 on 2020-05-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20200520_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capadeficiency',
            name='proposed_comletion_date',
        ),
        migrations.AddField(
            model_name='capadeficiency',
            name='proposed_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Proposed Completion Date'),
        ),
    ]
