# Generated by Django 3.0.6 on 2020-05-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_inspection_for_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='for_capa',
            field=models.BooleanField(default=False, verbose_name='CAPA Completed?'),
        ),
    ]
