# Generated by Django 3.0.6 on 2020-05-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20200521_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='for_capa',
            field=models.BooleanField(default=False),
        ),
    ]
