# Generated by Django 3.0.6 on 2020-06-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_auto_20200521_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa',
            name='recommendation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='capa',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='capadeficiency',
            name='action',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='capadeficiency',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='capadeficiency',
            name='inspector_comment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='type_of_inspection',
            field=models.CharField(choices=[('PLI', 'Post Licensing Inspection'), ('REN', 'Renewal of LTO'), ('INI', 'Initial Inspection'), ('RTN', 'Routine Inspection'), ('SPA', 'Special Assignment'), ('VTN', 'Variation')], max_length=20),
        ),
    ]
