# Generated by Django 3.0.6 on 2020-06-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_auto_20200608_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='remarks',
            field=models.TextField(help_text='Put inspection remarks here. Number each remark.', null=True),
        ),
    ]
