# Generated by Django 3.0.6 on 2020-07-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_auto_20200619_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='date_approved',
            field=models.DateField(blank=True, help_text='Format: YYYY/MM/DD', null=True, verbose_name='Date Approved by Supervisor'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='date_forwarded',
            field=models.DateField(blank=True, help_text='Format: YYYY/MM/DD', null=True, verbose_name='Date Forwarded to Supervisor'),
        ),
    ]
