# Generated by Django 3.0.6 on 2020-08-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_auto_20200814_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estinspector',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='est_inspectors', to='records.Inspection'),
        ),
    ]
