# Generated by Django 3.0.6 on 2020-08-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_auto_20200814_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='inspector',
        ),
    ]
