# Generated by Django 3.0.6 on 2020-08-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_remove_inspection_inspector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='type_of_inspection',
            field=models.CharField(choices=[('PLI', 'Post Licensing Inspection'), ('REN', 'Renewal of LTO'), ('INI', 'Initial Inspection'), ('RTN', 'Routine Inspection'), ('SPA', 'Special Assignment'), ('VTN', 'Variation'), ('CLS', 'For Verification of Closure')], max_length=250),
        ),
    ]
