# Generated by Django 3.0.6 on 2020-08-22 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_auto_20200819_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.TypeOfInspection', verbose_name='Type of Inspection'),
        ),
    ]
